services:
  tailscale:
    image: docker.io/tailscale/tailscale:latest
    container_name: tailscale-sidecar
    hostname: jellyfin-server
    restart: always
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATEFUL_FILTERING=false
    volumes:
      - tailscale-data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8096:8096
    cap_add:
      - NET_ADMIN
      - SYS_MODULE

  jellyfin:
    image: docker.io/jellyfin/jellyfin:latest
    container_name: jellyfin-container
    restart: always
    depends_on:
      - tailscale
    network_mode: "service:tailscale"
    userns_mode: "keep-id"
    user: "1000:1000"
    environment:
      - JELLYFIN_PublishedServerUrl=http://${JELLYFIN_IP}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    devices:
      - nvidia.com/gpu=all
    volumes:
      - ${CONFIG_PATH}:/config:Z
      - ${CACHE_PATH}:/cache:Z
      - ${MEDIA_PATH}:/media:ro,Z
    read_only: true
    tmpfs:
      - /tmp
      - /var/tmp
      - /run
      - /var/lib/jellyfin

volumes:
  tailscale-data:
